# Generated by Django 5.2.7 on 2025-11-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_favorite_productreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="moderator_notes",
            field=models.TextField(blank=True, help_text="Notes du modérateur"),
        ),
        migrations.AddField(
            model_name="productreview",
            name="report_reason",
            field=models.TextField(blank=True, help_text="Raison du signalement"),
        ),
        migrations.AddField(
            model_name="productreview",
            name="reported",
            field=models.BooleanField(default=False, help_text="Avis signalé"),
        ),
    ]
