# Generated by Django 5.2.7 on 2025-11-02 17:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_productreview_moderator_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code promo en majuscules", max_length=50, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description du code promo"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Pourcentage"),
                            ("fixed", "Montant fixe"),
                            ("free_shipping", "Livraison gratuite"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pourcentage (ex: 10) ou montant fixe (ex: 15.00)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "minimum_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Montant minimum de commande pour utiliser le code",
                        max_digits=10,
                    ),
                ),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_to", models.DateTimeField()),
                (
                    "max_usage",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Nombre maximum d'utilisations (0 = illimité)",
                    ),
                ),
                ("used_count", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "single_use_per_user",
                    models.BooleanField(
                        default=False, help_text="Une seule utilisation par utilisateur"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Catégories applicables (vide = toutes)",
                        to="shop.category",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Produits applicables (vide = tous)",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code promo",
                "verbose_name_plural": "Codes promo",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="shop.coupon",
            ),
        ),
    ]
