# Generated by Django 5.2.7 on 2025-11-02 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_order_discount_amount_order_shipping_cost_coupon_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vendeur",
            ),
        ),
    ]
