# Generated by Django 5.2.7 on 2025-11-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_product_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="wants_to_be_vendor",
            field=models.BooleanField(
                default=False, verbose_name="Souhaite devenir vendeur"
            ),
        ),
    ]
